wip

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -37,6 +37,10 @@ jobs:
         run: |
           # Find the first available simulator UDID and name
           device_info=$(xcrun simctl list devices available | grep -m 1 -E 'iPhone.*Simulator' | head -n 1)
+          if [ -z "$device_info" ]; then
+          echo "Error: No available iPhone simulators found."
+          exit 1
+          fi
           device_name=$(echo $device_info | sed -E 's/.*name:\s*([^,]+).*/\1/')
           device_udid=$(echo $device_info | sed -E 's/.*id:\s*([^,]+).*/\1/')
           echo "Using device: $device_name"
